import Head from "next/head";
import mongo from "../db/mongo";
import Data from "../models/Data";
import Link from "next/link";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1 className="my-3 text-center">Title</h1>

        <Link href="/new">
          <a className="btn btn-primary w-100 mb-3">Agregar</a>
        </Link>

        {data.map(({ title, _id, desc }) => (
          <div className="card mb-2" key={_id}>
            <div className="card-body">
              <p className="text-uppercase h5">{title}</p>
              <p className="fw-light">{desc}</p>
              <div>
                <Link href="/[id]/edit" as={`/${_id}/edit`}>
                  <a className="btn btn-warning me-2">Editar</a>
                </Link>
                <Link href="/[id]" as={`/${_id}`}>
                  <a className="btn btn-info">Visualizar</a>
                </Link>
              </div>
            </div>
          </div>
        ))}
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    await mongo();
    const result = await Data.find({});
    const data = result.map((doc) => {
      const datica = doc.toObject();
      datica._id = datica._id.toString();
      return datica;
    });
    return { props: { data } };
  } catch (error) {
    console.log(error);
  }
}
